CREATE TABLE Users(
	USER_ID 		VARCHAR2(100) NOT NULL UNIQUE,
	FIRST_NAME 		VARCHAR2(100) NOT NULL,
	LAST_NAME 		VARCHAR2(100) NOT NULL,
	YEAR_OF_BIRTH 	NUMBER(38),
	MONTH_OF_BIRTH	NUMBER(38),
	DAY_OF_BIRTH 	NUMBER(38),
	GENDER 			VARCHAR2(100),
	PRIMARY KEY 	(USER_ID) 
)

CREATE TABLE Hometown(
	HOMETOWN_CITY 		VARCHAR2(100),
	HOMETOWN_STATE		VARCHAR2(100),
	HOMETOWN_COUNTRY	VARCHAR2(100),
	PRIMARY KEY 		(HOMETOWN_CITY),
	USER_ID 			VARCHAR2(100) FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE CurrentLocation(
    CURRENT_CITY            VARCHAR2(100),
    CURRENT_STATE           VARCHAR2(100),
    CURRENT_COUNTRY         VARCHAR2(100),
    PRIMARY KEY 			(CURRENT_CITY),
    USER_ID 				VARCHAR2(100) FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE EduProgram (
	INSTITUTION_NAME			VARCHAR2(100),
	PROGRAM_YEAR				NUMBER(38),
	PROGRAM_CONCENTRATION 		CHAR(100),
	PROGRAM_DEGREE				VARCHAR2(100),
	PRIMARY KEY 				(INSTITUTION_NAME),
    USER_ID 					VARCHAR2(100) FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE Friendship(
    USER_ID 		VARCHAR2(100) FOREIGN KEY REFERENCES Users(USER_ID),
	FRIEND_ID 		VARCHAR2(100) NOT NULL UNIQUE,
	PRIMARY KEY 	(FRIEND_ID) 
	CONSTRAINT friend_constraint CHECK (FRIEND_ID <> USER_ID)
)

CREATE TABLE Album (
	ALBUM_ID			VARCHAR2(100) NOT NULL UNIQUE,
	OWNER_ID			VARCHAR2(100) NOT NULL,
	ALBUM_NAME			VARCHAR2(100),
	COVER_PHOTO_ID		VARCHAR2(100) NOT NULL, 
	ALBUM_CREATED_TIME	TIMESTAMP(6), 
	ALBUM_MODIFIED_TIME	TIMESTAMP(6),
	ALBUM_LINK			VARCHAR2(2000),
	ALBUM_VISIBILITY	VARCHAR2(100) CHECK(ALBUM_VISIBILITY='EVERYONE,' OR 
										   ALBUM_VISIBILITY='FRIENDS_OF_FRIENDS,' OR 
										   ALBUM_VISIBILITY='MYSELF,' OR 
										   ALBUM_VISIBILITY='CUSTOM,' ),
	PRIMARY KEY 		(ALBUM_ID)
)

CREATE TABLE Photo (
	PHOTO_ID			VARCHAR2(100) NOT NULL UNIQUE,
	PHOTO_CAPTION		VARCHAR2(2000),
	PHOTO_CREATED_TIME	TIMESTAMP(6),
	PHOTO_MODIFIED_TIME	TIMESTAMP(6),
	PHOTO_LINK			VARCHAR2(2000),
	PRIMARY KEY 		(PHOTO_ID)
)

CREATE TABLE PhotoTags(
	PHOTO_ID 			VARCHAR2(100) NOT NULL UNIQUE,
	TAG_SUBJECT_ID		VARCHAR2(100) UNIQUE,
	TAG_X_COORDINATE	NUMBER,
	TAG_Y_COORDINATE	NUMBER,
	TAG_CREATED_TIME	TIMESTAMP(6),
	PRIMARY KEY 		(PHOTO_ID)
)

CREATE TABLE Event  (
	EVENT_ID			VARCHAR2(100) NOT NULL UNIQUE,
	EVENT_CREATOR_ID	VARCHAR2(100) UNIQUE,
	EVENT_NAME			VARCHAR2(100),
	EVENT_TAGLINE		VARCHAR2(1000),
	EVENT_DESCRIPTION	VARCHAR2(4000),
	EVENT_HOST			VARCHAR2(100),
	EVENT_TYPE			VARCHAR2(100),
	EVENT_SUBTYPE		VARCHAR2(100),
	EVENT_LOCATION		VARCHAR2(200),
	EVENT_CITY			VARCHAR2(100),
	EVENT_STATE			VARCHAR2(100),
	EVENT_COUNTRY		VARCHAR2(100),
	EVENT_START_TIME	TIMESTAMP(6),
	EVENT_END_TIME		TIMESTAMP(6),
	PRIMARY KEY 		(EVENT_ID)
)

CREATE TABLE Event_Participants(
	USER_ID			VARCHAR2(100),
	STATUS			varchar(255),
	PRIMARY KEY		(USER_ID),
    EVENT_ID		VARCHAR2(100) FOREIGN KEY REFERENCES Event(EVENT_ID)
)
