CREATE TABLE Users(
	USER_ID 		int NOT NULL UNIQUE,
	FIRST_NAME 		varchar(255) NOT NULL,
	LAST_NAME 		varchar(255) NOT NULL,
	YEAR_OF_BIRTH 	DATE,
	MONTH_OF_BIRTH	DATE,
	DAY_OF_BIRTH 	DATE,
	GENDER 			varchar(255),
	PRIMARY KEY 	(USER_ID) 
)

CREATE TABLE Hometown(
	HOMETOWN_CITY 		varchar(255),
	HOMETOWN_STATE		varchar(255),
	HOMETOWN_COUNTRY	varchar(255),
	PRIMARY KEY 		(HOMETOWN_CITY),
	USER_ID 			int FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE CurrentLocation(
    CURRENT_CITY            varchar(255),
    CURRENT_STATE           varchar(255),
    CURRENT_COUNTRY         varchar(255),
    PRIMARY KEY 			(CURRENT_CITY),
    USER_ID 				int FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE EduProgram (
	INSTITUTION_NAME			varchar(255),
	PROGRAM_YEAR				int,
	PROGRAM_CONCENTRATION 		varchar(255),
	PROGRAM_DEGREE				varchar(255),
	PRIMARY KEY 				(INSTITUTION_NAME),
    USER_ID 					int FOREIGN KEY REFERENCES Users(USER_ID)
)

CREATE TABLE Friendship(
	FRIEND_ID 		int NOT NULL UNIQUE,
	PRIMARY KEY 	(FRIEND_ID) 
    USER_ID 		int FOREIGN KEY REFERENCES Users(USER_ID),
	CONSTRAINT friend_constraint CHECK (FRIEND_ID <> USER_ID)
)

CREATE TABLE Album (
	ALBUM_ID			int NOT NULL UNIQUE,
	OWNER_ID			int NOT NULL,
	ALBUM_NAME			varchar(255),
	COVER_PHOTO_ID		int NOT NULL, 
	ALBUM_CREATED_TIME	TIMESTAMP, 
	ALBUM_MODIFIED_TIME	TIMESTAMP,
	ALBUM_LINK			varchar(255),
	ALBUM_VISIBILITY	varchar(255) CHECK(ALBUM_VISIBILITY='EVERYONE,' OR 
										   ALBUM_VISIBILITY='FRIENDS_OF_FRIENDS,' OR 
										   ALBUM_VISIBILITY='MYSELF,' OR 
										   ALBUM_VISIBILITY='CUSTOM,' ),
	PRIMARY KEY 		(ALBUM_ID)
)

CREATE TABLE Photo (
	PHOTO_ID			int NOT NULL UNIQUE,
	PHOTO_CAPTION		varchar(255),
	PHOTO_CREATED_TIME	TIMESTAMP,
	PHOTO_MODIFIED_TIME	TIMESTAMP,
	PHOTO_LINK			varchar(255),
	PRIMARY KEY 		(PHOTO_ID)
)

CREATE TABLE PhotoTags(
	PHOTO_ID 			int NOT NULL UNIQUE,
	TAG_SUBJECT_ID		int UNIQUE,
	TAG_X_COORDINATE	int,
	TAG_Y_COORDINATE	int,
	TAG_CREATED_TIME	int,
	PRIMARY KEY 		(PHOTO_ID)
)

CREATE TABLE Event  (
	EVENT_ID			int NOT NULL UNIQUE,
	EVENT_CREATOR_ID	int UNIQUE,
	EVENT_NAME			varchar(255),
	EVENT_TAGLINE		varchar(255),
	EVENT_DESCRIPTION	varchar(255),
	EVENT_HOST			varchar(255),
	EVENT_TYPE			varchar(255),
	EVENT_SUBTYPE		varchar(255),
	EVENT_LOCATION		varchar(255),
	EVENT_CITY			varchar(255),
	EVENT_STATE			varchar(255),
	EVENT_COUNTRY		varchar(255),
	EVENT_START_TIME	TIMESTAMP,
	EVENT_END_TIME		TIMESTAMP,
	PRIMARY KEY 		(EVENT_ID)
)

CREATE TABLE Event_Participants(
	USER_ID			int,
	STATUS			varchar(255),
	PRIMARY KEY		(USER_ID),
    EVENT_ID		int FOREIGN KEY REFERENCES Event(EVENT_ID)
)
