DROP TABLE FRIENDSHIP;
DROP TABLE CUR_LOCATION;
DROP SEQUENCE cur_sequence;
DROP TABLE EDUPROGRAM;
DROP SEQUENCE edu_sequence;

DROP TABLE EVENT;

DROP TABLE HOME_LOCATION;
DROP TABLE USERS;
DROP SEQUENCE home_sequence;

DROP TABLE ALBUM_MEMBERS;
DROP TABLE PHOTOTAGS;
DROP SEQUENCE tag_sequence;
DROP TABLE PHOTO;
DROP TABLE ALBUM;


DROP TABLE EVENT_PARTICIPANTS;
