/*
  EECS 484 Project 1
  Galen Gong (ggong)
  Aditi Rajagopal (araja)
*/

DROP TABLE FRIENDSHIP;
DROP TABLE CUR_LOCATION;
DROP SEQUENCE cur_sequence;
DROP TABLE EDUPROGRAM;
DROP SEQUENCE edu_sequence;

DROP TABLE EVENT;

DROP TABLE HOME_LOCATION;
DROP SEQUENCE home_sequence;

DROP TABLE ALBUM_COVERPHOTO;
DROP TABLE PHOTOTAGS;
DROP SEQUENCE tag_sequence;
DROP TABLE PHOTO;

DROP TABLE EVENT_PARTICIPANTS;
DROP TABLE ALBUM;
DROP TABLE USERS;

DROP TABLE PUBLIC_USER_INFORMATION;
DROP TABLE PUBLIC_ARE_FRIENDS;
DROP TABLE PUBLIC_PHOTO_INFORMATION;
DROP TABLE PUBLIC_TAG_INFORMATION;
DROP TABLE PUBLIC_EVENT_INFORMATION;