DROP TABLE FRIENDSHIP;
DROP TABLE CUR_LOCATION;
DROP TABLE EDUPROGRAM;

DROP TABLE EVENT;

DROP TABLE USERS;
DROP TABLE HOME_LOCATION;

DROP TABLE ALBUM_MEMBERS;
DROP TABLE PHOTOTAGS;
DROP TABLE PHOTO;
DROP TABLE ALBUM;


DROP TABLE EVENT_PARTICIPANTS;
