INSERT INTO USERS(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER)
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER FROM
PUBLIC_USER_INFORMATION;

INSERT INTO HOME_LOCATION (CITY, STATE, COUNTRY)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY FROM 
PUBLIC_USER_INFORMATION;

INSERT INTO CUR_LOCATION (CITY, STATE, COUNTRY)
SELECT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY FROM 
PUBLIC_USER_INFORMATION;

INSERT INTO EDUPROGRAM (INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
SELECT INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE FROM 
PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDSHIP (USER_ID, FRIEND_ID)
SELECT DISTINCT USER1_ID, USER2_ID FROM 
PUBLIC_USER_INFORMATION
WHERE USER1_ID != USER2_ID

INSERT INTO Album (ALBUM_ID, OWNER_ID, ALBUM_NAME, COVER_PHOTO_ID, ALBUM_CREATED_TIME,
	ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY)
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, COVER_PHOTO_ID, ALBUM_CREATED_TIME,
	ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY FROM 
PUBLIC_PHOTO_INFORMATION;

INSERT INTO Photo (PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
SELECT DISTINCT PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK FROM 
PUBLIC_PHOTO_INFORMATION;

INSERT INTO ALBUM_MEMBERS (PHOTO_ID, ALBUM_ID)
SELECT DISTINCT PHOTO_ID, ALBUM_ID FROM 
PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOTAGS(TAG_SUBJECT_ID, TAG_X_COORDINATE, TAG_Y_COORDINATE, TAG_CREATED_TIME)
SELECT DISTINCT TAG_SUBJECT_ID, TAG_X_COORDINATE, TAG_Y_COORDINATE, TAG_CREATED_TIME FROM
PUBLIC_TAG_INFORMATION;

INSERT INTO Event(EVENT_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST,
	EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME,
	EVENT_END_TIME)
SELECT DISTINCT EVENT_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST,
	EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME,
	EVENT_END_TIME
	FROM
PUBLIC_EVENT_INFORMATION;
